package ru.petkeeper.database.pets_table

data class PetDto(
    val id: Int = -1,
    val name: String = "",
    val type: String = "",
    val breed: String = "",
    val gender: String = "",
    val years: Int = 1,
    val months: Int = 1,
    val weight: Double = 1.0,
    val isFriendlyToPeople: Boolean? = false,
    val isFriendlyToChildren: Boolean? = false,
    val isFriendlyToCats: Boolean? = false,
    val isFriendlyToDogs: Boolean? = false,
    val isFriendlyToOtherAnimals: Boolean? = false,
    val canLiveWithDogs: Boolean = false,
    val canLiveWithCats: Boolean = false,
    val canLiveWithOtherAnimals: Boolean = false,
    val isLitterBoxTrained: Boolean = false,
    val marksThings: Boolean = false,
    val chewsThings: Boolean = false,
    val isVaccinated: Boolean = false,
    val isSterilised: Boolean = false,
    val diseases: String = "",
    val canStayAlone: Boolean = false,
    val foodToEat: String = "",
    val foodToAvoid: String = "",
    val howOftenToFeed: String = "",
    val needsWalking: Boolean = false,
    val howOftenToWalk: String? = "",
    val warningsWhileWalking: String? = "",
    val needsPlaying: Boolean = false,
    val howToPlay: String? = "",
    val howToWash: String = "",
    val otherRecs: String = "",
    val picture: ByteArray? = null
)